########################################################################
# Spring JPA configuration
########################################################################
spring:
  thymeleaf:
    cache: false
    mode: HTML
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace


##################################################################
# Multi-Tenancy Master Database Set Up
##################################################################
multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/masterdb
        username: tester
        password: tester
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 10
        idleTimeout: 300000
        minIdle: 10
        poolName: masterdb-connection-pool

##################################################################
# Logging Levels
##################################################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE